### ISSUE TITLE
Logging Enhancements

### ISSUE THREAD

**Issue by davidlmorton** [genome/ptero-lsf#51]
The following principles need to be adhered to:

1. Context should always logged if available.
  * Job ID
  * Parts of POST body relevant to know one job from another
2. Both sides of every handoff of control should be logged at the INFO level.
  * accepting job POST
  * before submitting task to celery
  * accepting task from celery
  * returning value of task to celery
  * sending webhook
3. DEBUG level should show data that flows through each handoff (truncating if needed).
4. All exceptions should be logged unless handled in normal course of action.
  * Should be able justify use of exceptions in those cases.
5. Logical steps should be logged at the DEBUG level, just BEFORE they occur.
  * This is especially important for long running steps.

**Comment by mkiwala** [comment]
You mentioned truncating.  The deis logspout syslogStreamer sets the write buffer size to [1048576](https://github.com/mkiwala/deis/blob/heat-template/logspout/logspout.go#L72).  Log lines that are too long will kill logspout when logspout is using the syslogStreamer, as we do in our deployment to send logs to logstash.

**Comment by mkiwala** [comment]
If we import flask in the backend, then flask must be installed in the virtualenv for the celery workers which use the backend.
