### ISSUE TITLE
PollActiveJobs should not queue so many updates

### ISSUE THREAD

**Issue by mkiwala** [genome/ptero-lsf#52]
PollActiveJobs should not queue updates for jobs which having a queued updated already pending.

Currently, when the status updating process is not updating statuses fast enough or at all, PollActiveJobs will continue queueing additional status update tasks for lsf jobs which already have a status update task in the celery queue.

This would probably be implemented with an internal ptero-lsf status for jobs which indicates that a status update is pending.

**Comment by davidlmorton** [comment]
Since status updates get recorded in the status history, I think a new column (such as 'lsf-status-pending') might be better.
