### ISSUE TITLE
investigate celery consuming messages after exceptions

### ISSUE THREAD

**Issue by davidlmorton** [genome/ptero-lsf#71]
We thought that acks-late would prevent this, but perhaps there are other settings we need to change.

**Comment by mkiwala** [comment]
I came across [this article](http://www.lshift.net/blog/2015/04/30/making-celery-play-nice-with-rabbitmq-and-bigwig/) over the weekend.  The article suggests enabling a rabbitmq feature called publisher confirms.  [Publisher confirms](http://www.rabbitmq.com/blog/2011/02/10/introducing-publisher-confirms/) can be enabled through celery configuration, by setting the `BROKER_TRANSPORT_OPTIONS = {'confirm_publish': True}` option.

Unrelated to this issue, but also in this article is the recommendation to enable the `BROKER_HEARTBEAT` which is disabled by default.  I think this option would help celery detect when openstack networking is broken and the work tcp/ip connection to rabbitmq must be re-established.

**Comment by davidlmorton** [comment]
According to the Celery documentation the ACKS_LATE feature only protects you from an exception within the celery worker code itself, an exception in the Task is different.  There, the exception will be caught, the message acked and the Task considered failed.  If we want to retry in those situations we either need to kill the worker process hard, or explicitly catch the exception and stipulate a retry.
