### ISSUE TITLE
Set status to `ERRORED` when failed update count reaches MAX_FAILS

### ISSUE THREAD

**Issue by mkiwala** [genome/ptero-lsf#98]
Setting this status would signal that there is something wrong with the job and it will never be updated to `succeeded` or `failed`.  Also, in case the job was submitted from ptero-workflow (practically always), setting this status will also trigger the `errored` webhook back to workflow, which will cause the workflow to fail instead of sitting in a stale `running` status.

**Comment by davidlmorton** [comment]
+1 I thought we already did this :(
